version: '3.7'
services:
  grafana:
    image: grafana/grafana-enterprise:${GF_VERSION:-8.4.7}
    ports:
      - '3000:3000'
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-guidedtour-panel
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_ENTERPRISE_LICENSE_TEXT=$GF_ENTERPRISE_LICENSE_TEXT