version: '3.7'
services:
  grafana:
    container_name: 'grafana-guidedtour-panel'
    image: grafana/grafana-enterprise:${GF_VERSION:-8.4.7}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-guidedtour-panel
      - ./provisioning/dashboards-actual:/dashboards
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_PANELS_ENABLE_ALPHA=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_VIEWERS_CAN_EDIT=true
      - GF_ENTERPRISE_LICENSE_TEXT=$GF_ENTERPRISE_LICENSE_TEXT